### ISSUE TITLE
By Bayu12345677 msg for you

### ISSUE THREAD

**Issue by Bayu12345677** [KhanhNguyen9872/Flappy_Bird_CPP#1]
brother please don't deobfuscate my script if I don't ask 

many people out there are taking advantage of your abilities to steal my source code

maybe you can help me create an obfuscate tool to secure bash scripts I've been developing for several years maybe you can contribute in the pyramid obf repository that you have deobfuscated

from me Bayu12345677

**Comment by KhanhNguyen9872** [comment]
> brother please don't deobfuscate my script if I don't ask
> 
> many people out there are taking advantage of your abilities to steal my source code
> 
> maybe you can help me create an obfuscate tool to secure bash scripts I've been developing for several years maybe you can contribute in the pyramid obf repository that you have deobfuscated
> 
> from me Bayu12345677

deleted all except [Piramid-obf](https://github.com/KhanhNguyen9872/Piramid-obf_src)
i will not contribute because when i know how to deobfuscate it, there no way to obf

**Comment by KhanhNguyen9872** [comment]
> brother please don't deobfuscate my script if I don't ask
> 
> many people out there are taking advantage of your abilities to steal my source code
> 
> maybe you can help me create an obfuscate tool to secure bash scripts I've been developing for several years maybe you can contribute in the pyramid obf repository that you have deobfuscated
> 
> from me Bayu12345677

stop coding .sh script, go to coding python and use this [bot](https://t.me/khanhnguyen9872_bot) to obfuscate your source code, don't try to add .sh script into python script look like your previous repo

**Comment by Bayu12345677** [comment]
okay thanks for the advice for now I can't leave bash on because some features in bash don't exist in python
