### ISSUE TITLE
mainmenu.wav

### ISSUE THREAD

**Issue by 0xTOHO** [KhanhNguyen9872/Flappy_Bird_CPP#2]
ơ ông biết tên nhạc đấy là gì không nghe hay đấy :)))

**Comment by KhanhNguyen9872** [comment]
> ơ ông biết tên nhạc đấy là gì không nghe hay đấy :)))

[mainmenu.wav](https://youtu.be/dkoaFo3CN4Y)

**Comment by redsox2004rbg** [comment]
hello
